# Generated by Django 3.1.3 on 2025-03-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExeFit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='tx_hash',
            field=models.CharField(default='0x0000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('yearly', 'Yearly')], default='Yearly', max_length=50, unique=True),
        ),
    ]
