# Generated by Django 3.1.3 on 2025-03-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExeFit', '0002_auto_20250324_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
    ]
