# Generated by Django 3.1.3 on 2025-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExeFit', '0003_remove_membership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('yearly', 'Yearly')], default='Yearly', max_length=50, unique=True),
        ),
    ]
