# Generated by Django 3.1.3 on 2025-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExeFit', '0004_membership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration_days',
            field=models.IntegerField(default=365, editable=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('yearly', 'Yearly')], default='yearly', max_length=50, unique=True),
        ),
    ]
