# Generated by Django 3.1.3 on 2025-03-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExeFit', '0005_auto_20250324_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check_in_count',
            field=models.IntegerField(default=0),
        ),
    ]
