# Generated by Django 3.1.3 on 2025-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExeFit', '0006_userprofile_check_in_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('yearly', 'Yearly')], default='yearly', max_length=50),
        ),
    ]
